### ISSUE TITLE
python3 issue during setup.py test

### ISSUE THREAD

**Issue by FlyinTeller** [brentp/python-giggle#2]
I used a fresh miniconda3 python 3.6 environment in which i tried to install python-giggle. I pip installed cython and numpy. However when I run `setup.py test` I get the error:

```
======================================================================
ERROR: <nose.suite.ContextSuite context=test_giggle>
test suite for <module 'test_giggle' from '/home/CODE1/320000451/Software/python-giggle/giggle/tests/test_giggle.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/CODE1/320000451/Software/python-giggle/.eggs/nose-1.3.7-py3.6.egg/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/CODE1/320000451/Software/python-giggle/.eggs/nose-1.3.7-py3.6.egg/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/CODE1/320000451/Software/python-giggle/.eggs/nose-1.3.7-py3.6.egg/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/CODE1/320000451/Software/python-giggle/.eggs/nose-1.3.7-py3.6.egg/nose/util.py", line 471, in try_run
    return func()
  File "/home/CODE1/320000451/Software/python-giggle/giggle/tests/test_giggle.py", line 18, in setup
    Giggle.create(INDEX, "lib/giggle/test/data/many/*.bed.gz")
  File "giggle/giggle.pyx", line 25, in giggle.giggle.Giggle.create
    def create(self, char *path, char *glob):
TypeError: expected bytes, str found

```
The issue is probably that `"lib/giggle/test/data/many/*.bed.gz"` is a unicode string and not a byte string in python3. Is the software only intended for use with python2 or will I be able to just use it with python3? `setup.py install` seems to be working fine and in my own code I could make sure to always explicitly convert to byte strings

**Comment by mattievk** [comment]
The test and setup went fine in my miniconda python3.6 environment. But I get the same type error when running the `Giggle.create` function in python 3.7 using some .bed files.  Is it trivial to convert the bed files to byte strings in order to use giggle with python3.6?

**Comment by brentp** [comment]
Thanks for reporting. I'll have a look at supporting python3.

**Comment by brentp** [comment]
I have pushed a fix for this. Please give it a try.

**Comment by FlyinTeller** [comment]
Thanks @brentp for the quick reply
